# Créditos {.unnumbered}

## Expediente {.unnumbered}

Presidente da República Federativa do Brasil\
**Luiz Inácio Lula da Silva**

Ministro de Estado do Desenvolvimento e Assistência Social, Família e Combate à Fome\
**Wellington Dias**

Secretário-Executivo\
**Osmar Ribeiro de Almeida Júnior**

Secretária Extraordinária de Combate à Pobreza e à Fome\
**Valéria Torres Amaral Burity**

Secretário de Avaliação, Gestão da Informação e Cadastro Único\
**Rafael Guerreiro Osório**

Secretária Nacional de Renda de Cidadania\
**Eliane Aquino Custodio**

Secretária Nacional de Segurança Alimentar e Nutricional\
**Lilian dos Santos Rahal**

Secretário de Inclusão Socioeconômica\
**Luiz Carlos Everton de Farias**

Secretária Nacional da Política de Cuidados e Família\
**Laís Wendel Abramo**

Secretária Nacional de Assistência Social\
**Rosilene Cristina Rocha **

Secretário Nacional de Benefícios Assistenciais\
**Amarildo Baesso**

Secretária Nacional de Integração e Articulação de Plataformas Sociais Eletrônicas\
**Analúcia Faggion Alonso **

---

## Ficha Técnica {.unnumbered}

### Coordenação-Geral da Publicação do Censo SUAS 2024 {.unnumbered}

**Diretoria de Monitoramento e Avaliação - DMA/SAGICAD:**\
- Cecília Piva: Coordenadora-Geral

**Diretoria de Gestão do SUAS -- DGSUAS/SNAS**\
- Clara Carolina de Sá: Diretora de Gestão do SUAS

### Coordenação-Geral do Censo SUAS 2024 {.unnumbered}

Paulo Clemente - Coordenador-Geral de Planejamento e Vigilância Socioassistencial.

### Desenvolvimento de projeto de programação, análise de dados e produção da publicação; coordenação, elaboração e revisão dos textos  {.unnumbered}

Cecília Piva, Isabela Joanol Dias da Silva, Lucas Abrantes, Shirley Samico e Valdson Silva Cleto

### Desenvolvimento de aplicativos informatizados, coleta e tratamento de dados do Censo SUAS 2024 {.unnumbered}

André Saraiva, Caio Nakashima, Carlos Henrique Santana, Carlos Brasileiro, Caroline Sampaio, Cinthia Miranda, Cristiane Silva de Moura, Danilo Galvão da Cunha, Davi Lopes Carvalho, Daniela Ramos, Débora Macedo, Dionara Borges, Érika Paes Latim Castro, Frederico Palma, João Sobrinho, Lana Barbosa, Letícia Fonseca, Luis Otavio Farias, Marcelo do Nascimento Saraiva, Marcelo Gadelha, Marcos Coimbra, Marco Rodrigo Carvalho, Marcos Maia Antunes, Marina Brito, Murilo da Silva Mascarenhas de Morais, Paulo Clemente, Pedro Henrique Ribeiro Ferreira, Ricardo Carvalho, Roberto Wagner, Sabrina Borges, Tássio Fialho, Tiago Hackbarth.

---

## Como Citar esta Publicação

Para fins de citação bibliográfica e consistência metodológica em pesquisas científicas, recomenda-se a utilização dos formatos padronizados abaixo:

::: {.callout-note appearance="simple" icon=false}
**Padrão ABNT (Para a Edição Específica de 2024)**  
BRASIL. Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome. **Censo SUAS 2024: análise dos componentes sistêmicos da Política Nacional de Assistência Social**. Brasília, DF: MDS, 2026. e-ISSN [INSERIR-ISSN-AQUI]. Disponível em: <https://www.gov.br/mds/pt-br/orgaos/SAGICAD/estudos-e-pesquisas/censo-suas-2024>. Acesso em: `r format(Sys.Date(), "%d %b. %Y")`. DOI: [INSERIR-LINK-DO-DOI-AQUI].

<br>

**Padrão ABNT (Coleção / Série Geral)**  
BRASIL. Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome. **Censo SUAS: análise dos componentes sistêmicos da Política Nacional de Assistência Social**. Brasília, DF: MDS, 2010-. Publicação impressa e eletrônica (2010-2022); exclusivamente eletrônica a partir de 2023. e-ISSN [INSERIR-ISSN-AQUI]. Disponível em: <https://www.gov.br/mds/pt-br/orgaos/SAGICAD/estudos-e-pesquisas/censo-suas>. Acesso em: `r format(Sys.Date(), "%d %b. %Y")`.
:::

---

## Dados Internacionais de Catalogação na Publicação (CIP)

Informações de registro geradas em conformidade com as diretrizes internacionais de catalogação para recursos contínuos eletrônicos:

| Atributo | Detalhes da Publicação |
| :--- | :--- |
| **Entidade Responsável** | Brasil. Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome. Secretaria Nacional de Assistência Social. Secretaria de Avaliação, Gestão da Informação e Cadastro Único. |
| **Título Oficial** | Censo SUAS 2024: análise dos componentes sistêmicos da Política Nacional de Assistência Social |
| **Local de Publicação** | Brasília, DF |
| **Ano de Publicação** | 2026 |
| **Identificador Periódico**| e-ISSN [INSERIR-ISSN-AQUI] (Versão Online) |
| **Periodicidade** | Anual |
| **Assuntos / Palavras-chave** | 1. Assistência Social — Brasil.<br>2. Censo – Aspectos sociais.<br>3. Políticas públicas sociais.<br>4. Sistema Único de Assistência Social (SUAS). |
| **Classificação Temática** | CDD: 362.0981 |
| **Responsabilidade Técnica** | Catalogação elaborada por Aline Graziele Benitez – Bibliotecária - CRB-1/3129 |

: { .hover .tbl-colwidths="" }

---

::: {.column-screen-inset-right}
<small>
*Última atualização deste documento: `r format(Sys.Date(), "%d/%m/%Y")`.*  
*O Censo SUAS é uma publicação oficial de acesso aberto. Textos e dados podem ser reproduzidos livremente, desde que citada a fonte.*
</small>
:::

<!-- ## Ficha Catalográfica {.unnumbered} -->

```{r}
#| include: false

htmltools::HTML('
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <link href="../Styles/idGeneratedStyles.css" rel="stylesheet" type="text/css"/>
    <link href="../Styles/estilo_geral.css" rel="stylesheet" type="text/css"/>
    
  <style>
        
p.ficha-centro {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:1em;
    font-style:normal;
    font-variant:normal;
    font-weight:normal;
    line-height:1.15;
    margin-bottom:0;
    margin-left:0;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:center;
    text-decoration:none;
    text-indent:0;
    text-transform:none;
    widows:1;
}
        
p.ficha-centro-11 {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:0.917em;
    font-style:normal;
    font-variant:normal;
    font-weight:normal;
    line-height:1.15;
    margin-bottom:0;
    margin-left:0;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:center;
    text-decoration:none;
    text-indent:0;
    text-transform:none;
    widows:1;
}

p.ficha-esq {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:0.917em;
    font-style:normal;
    font-variant:normal;
    font-weight:normal;
    line-height:1.5;
    margin-bottom:0;
    margin-left:0;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:left;
    text-decoration:none;
    text-indent:0;
    text-transform:none;
    widows:1;
}
        
p.ficha-autor {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:0.917em;
    font-style:normal;
    font-variant:normal;
    font-weight:normal;
    line-height:1.5;
    margin-bottom:0;
    margin-left:4.8em;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:left;
    text-decoration:none;
    text-indent:-1.8em;
    text-transform:none;
    widows:1;
}

p.ficha {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:0.917em;
    font-style:normal;
    font-variant:normal;
    font-weight:normal;
    line-height:1.5;
    margin-bottom:0;
    margin-left:3em;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:left;
    text-decoration:none;
    text-indent:1.8em;
    text-transform:none;
    widows:1;
}

p.ficha-ca {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:1em;
    font-style:normal;
    font-variant:normal;
    font-weight:bold;
    line-height:1.5;
    margin-bottom:0;
    margin-left:0;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:center;
    text-decoration:none;
    text-indent:0;
    text-transform:none;
    widows:1;
}

p.ficha-center-bold-11 {
  -webkit-hyphens: none !important; 
  adobe-hyphenate: none; 
  -moz-hyphens: none; 
  hyphens: none; 
    font-family:"Courier New", courier, monospace;
    font-size:0.917em;
    font-style:normal;
    font-variant:normal;
    font-weight:bold;
    line-height:1.5;
    margin-bottom:0;
    margin-left:0;
    margin-right:0;
    margin-top:0;
    orphans:1;
    page-break-after:auto;
    page-break-before:auto;
    text-align:center;
    text-decoration:none;
    text-indent:0;
    text-transform:none;
    widows:1;
}
        
div.ficha {
    border-width:1px;
    border-style:solid;
  padding:0.3em;
    margin:.8em auto 1em auto;
}
        
div.caixa-ficha {
  text-align:center;
}
        
div.grupo {
  display:inline-block;
  width:80%;
  margin:0 auto;
}
        
table.ficha, table.ficha tr, table.ficha td { 
  border:0;
}

div.tabela-ficha {
  text-align:center;
}

table.ficha {
  display:inline-table;
  margin:1em 0;
}
    
  </style>
    </head>

<body xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <div class="caixa-ficha">
        <div id="_idContainer004" class="grupo">
            <p class="ficha-centro">Dados Internacionais de Catalogação na Publicação (CIP)</p>
            <p class="ficha-ca">(BENITEZ Catalogação Ass. Editorial, MS, Brasil)</p>
            
      <!-- #################### FICHA ###################### -->
      
            <div class="ficha" id="_idContainer003">
                <p class="ficha">   <br/></p>
                <p class="ficha-autor">Brasil. Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome. Secretaria Nacional de Assistência Social. Secretaria de Avaliação, Gestão da Informação e Cadastro Único.</p>
                <p class="ficha">   Censo SUAS 2022 : análise dos componentes sistêmicos da Política Nacional de Assistência Social / coordenação geral Joana Simões de Melo Costa, Shirley de Lima Samico ; concepção e organização de textos Clara Carolina de Sá e Shirley Samico. -- 1.ed. –  Brasília, DF : Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome, 2024. </p>
                <p class="ficha">   HTML<br/><br/></p>
                <p class="ficha">   Vários colaboradores.</p>
                <p class="ficha">   Bibliografia.</p>
                <p class="ficha">   ISBN 978-65-01-01956-7<br/><br/></p>
                <p class="ficha">   1. Assistência social – Brasil. 2. Censo – Aspectos sociais. 3. Políticas públicas sociais. 4. Sistema Único de Assistência Social (SUAS). I. Costa, Joana Simões de Melo. II. Samico, Shirley de Lima. III. Sá, Clara Carolina de. IV. Silva, Elizangela Cardoso de Araújo.<br/><br/></p>
                <p class="ficha-esq">
                  12-2024/94
                  <span style="float: right;">
                    CDD 362.0981
          </span>
                </p>
            </div>
        
      <!-- #################### ENDEREÇO ###################### -->
          <div id="_idContainer005 grupo">
                <p class="ficha">   <br/></p>
        <p class="ficha-center-bold-11">Índice para catálogo sistemático:</p>
              <p class="ficha-centro-11">1. Brasil : Assistência social : Políticas públicas : Problemas sociais   362.0981</p>
        <p class="ficha-center-bold-11">Aline Graziele Benitez – Bibliotecária - CRB-1/3129</p>
          </div>
        </div>
    </div>
</body>
')
```
