# Prefácio {.unnumbered}

Ao longo de mais de três décadas desde a promulgação da Lei Orgânica da Assistência Social (LOAS) e de vinte anos da implementação do Sistema Único de Assistência Social (SUAS), a Política de Assistência Social tem consolidado avanços expressivos, perceptíveis na vida da população brasileira. Dada a importância e necessidade de aprofundamento de tais avanços, é neessário que eles sejam também mensuráveis, por meio da consolidação de processos contínuos e consistentes de gestão da informação, monitoramento e avaliação.

Garantir o pleno funcionamento do ciclo das políticas públicas é um compromisso permanente do nosso governo. No âmbito da Assistência Social, essa responsabilidade é exercida por meio da Vigilância Socioassistencial, que abrange a coleta de dados, o monitoramento, a avaliação e a ampla disseminação das informações produzidas — tanto para aqueles que as geram quanto para os que as utilizam, incluindo gestores, pesquisadores, instâncias de Controle Social e a sociedade em geral. 

O Censo SUAS é essencial para qualificar a compreensão sobre a Política de Assistência Social. Uma fonte única de informações, ele permite o acompanhamento da gestão financeira e orçamentária, da estrutura administrativa e do funcionamento das instâncias responsáveis pelo Cadastro Único nos estados, municípios e no Distrito Federal, bem como da gestão do trabalho, da oferta e da qualidade dos serviços e unidades que compõem o SUAS.

O Censo reúne informações sobre a execução de serviços, benefícios e programas socioassistenciais, além de evidenciar o papel do Controle Social na política — contribuindo, assim, para o aprimoramento das ações e para um atendimento cada vez mais qualificado à população.

Apresentando dados referentes ao ano de 2023 que garantem a atualização de informações longitudinais sobre o SUAS, esta é a décima edição da publicação, cuja primeira versão foi lançada em 2010. Nela, a gestão das informações, foi aprimorada com a adoção do sistema R Markdown, posteriormente atualizado para a ferramenta Quarto — inovação que assegura maior consistência e transparência na geração dos dados e gráficos, por meio do registro preciso, na linguagem R, de todas as etapas de produção.

Esperamos que esta publicação sirva de subsídio a gestoras(es), trabalhadoras(es), conselheiras(os) e pesquisadoras(es) envolvidas(os) com o SUAS, contribuindo para o fortalecimento dos debates e das práticas no campo da Assistência Social. O Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome (MDS), por meio da SAGICAD e da SNAS, reafirma seu compromisso com o fortalecimento do SUAS e manifesta profunda estima a todas e todos que, cotidianamente, se dedicam à consolidação e ao avanço dessa política pública essencial.

Rafael Osório

Secretário de Avaliação, Gestão da Informação e Cadastro Único

André Quintão

Secretária Nacional de Assistência Social
